# Generated by Django 2.0 on 2018-03-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_senha_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo_funcionario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='usuarios.Cargo'),
            preserve_default=False,
        ),
    ]
