# Generated by Django 2.0 on 2018-03-22 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180321_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='empresa_funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='usuarios.Empresa'),
        ),
    ]
