# Generated by Django 2.0 on 2018-03-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180321_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='usuarios.Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='usuarios.Empresa'),
        ),
    ]
