# Generated by Django 2.0 on 2018-03-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180321_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha_acesso',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
