# Generated by Django 2.0 on 2018-03-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_funcionario_senha_acesso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_empresa',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_funcionario',
            new_name='nome',
        ),
    ]
