# Generated by Django 2.0 on 2018-03-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180321_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='email_empresa',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefone_empresa',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='email_funcionario',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='telefone_funcionario',
            new_name='telefone',
        ),
    ]
