# Generated by Django 2.0 on 2018-03-22 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0008_auto_20180321_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoNovaSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.CharField(max_length=6)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
