# Generated by Django 2.0 on 2018-03-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_solicitacaonovasenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaonovasenha',
            name='fechada',
            field=models.BooleanField(default=False),
        ),
    ]
