# Generated by Django 2.0 on 2018-03-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_solicitacaonovasenha_fechada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaonovasenha',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='SolicitacaoNovaSenha',
        ),
    ]
