# Generated by Django 2.0 on 2018-03-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('email_fornecedor', models.EmailField(max_length=255)),
                ('telefone_fornecedor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('sigla_nome_marca', models.CharField(max_length=255)),
                ('descricao_marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(max_length=255)),
                ('preco_unitario', models.FloatField()),
                ('preco_atacado', models.FloatField()),
                ('qtd_minima', models.IntegerField()),
                ('qtd_estoque', models.IntegerField()),
                ('categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='produtos.Categoria')),
                ('fornecedor_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='produtos.Fornecedor')),
                ('marca_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='produtos.Marca')),
            ],
        ),
    ]
