# Generated by Django 2.0 on 2018-03-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20180323_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='projetos.Usuario'),
            preserve_default=False,
        ),
    ]
