# Generated by Django 2.0 on 2018-03-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_projeto_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(through='projetos.Usuario_Projeto', to='projetos.Usuario'),
        ),
    ]
