# Generated by Django 2.0 on 2018-03-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_auto_20180323_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
    ]
