# Generated by Django 2.0 on 2018-03-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_auto_20180323_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
    ]
