# Generated by Django 2.0 on 2018-03-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_auto_20180323_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
    ]
